sudo: false
language: node_js
go:
    - 1.5.1
node_js:
    - "4.0"
      #    - "4.1"
      #    - "0.12"
      #    - "0.10"
env :
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install: 
    - ./install.sh
script: 
    - ./build.sh
